version: "3.7"

services:
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - core-redis:/var/lib/redis/data

  core:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./core
        target: /app/core
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq 
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./core
        target: /app/core
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - core
    ports:
      - '8020:8020'

volumes:
  core-redis:
